### ISSUE TITLE
Update the custom simplified version of redux to use the new context API

### ISSUE THREAD

**Issue by horacioh** [reactjsacademy/fb-messenger#5]
if you go to the `redux` branch, there's an exercise that you need to implement your own version of redux. this version of redux is using the old context API, so the goal is to refactor the code and Implement the new version of the context API.

## Files that you need to modify:
- `/src/react-redux/connect.js`
- `/src/react-redux/Provider.js`

you can follow the Official documentation here: https://reactjs.org/docs/context.html

## Tasks
- [ ] refactor code in `redux` [branch](https://github.com/leanjscom/fb-messenger/tree/redux)
- [ ] refactor code in `redux-leanjs-part1` [branch](https://github.com/leanjscom/fb-messenger/tree/redux-leanjs-part1)
- [ ] refactor code in `redux-leanjs-part2` [branch](https://github.com/leanjscom/fb-messenger/tree/redux-leanjs-part2)

any questions please let us know! :)
